headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\CascadeProjects\\rise-at-seven-replica"
publishOrigin = "config"
base = "C:\\Users\\User\\CascadeProjects\\rise-at-seven-replica"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"